import Head from "next/head";
import Navbar from "@/Components/Navbar";
import Home from "@/Components/Home";
import Iconbox from "@/Components/Iconbox";
import About from "@/Components/About";
import Mission from "@/Components/Mission";
import Industries from "@/Components/Industries";
import Services from "@/Components/Services";
import Products from "@/Components/Products";
import Contact from "@/Components/Contact";
import Blog from '@/Components/Blog';
import Footer from "@/Components/Footer";





export default function main() {
  return (
    <>
      <Head>
        <title>Red Secureme</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/tabicon.png"/>

      </Head>

      <Navbar/>
      <Home/>
      <Iconbox/>
      <About/>
      <Mission/>
      <Industries/>
      <Services/>
      <Products/>
      <Contact/>
      <Blog/>
      <Footer/>





    
    </>
  );
}
